{% set name = "omnipkg" %}
{% set version = "1.5.3" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1d0be6483a0aac544cefda47323fe5442782d240ed1e54c247b76ac15de3835
  
build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps --no-build-isolation -vv"
  entry_points:
    - omnipkg = omnipkg.cli:main
    - 8pkg = omnipkg.cli:main
requirements:
  host:
    - python >=3.9,<3.14
    - pip
    - setuptools >=61.0
  run:
    - python >=3.9,<3.14
    - packaging >=21.0
    - requests >=2.20
    - authlib >=1.6.4
    - filelock >=3.9
    - tomli  # python_version<"3.11"
    - safety >=2.3.5
    - aiohttp
    - uv
test:
  imports:
    - omnipkg
  commands:
    - omnipkg --version
about:
  home: https://github.com/1minds3t/omnipkg
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver. One environment. Infinite packages. Zero conflicts.'
  description: |
    Omnipkg is a next-generation Python manager engineered for speed, solving
    dependency hell by allowing multiple package and Python versions to coexist
    and swap instantly in a single environment.

    This version introduces major performance upgrades and powerful new environment
    repair tools for demanding, high-throughput workflows.

    Key Features:
      • **NEW `doctor`/`heal` Commands:** Surgically repair corrupted environments and
        automatically reconcile complex dependency conflicts.
      
      • **High-Speed Concurrency:** A rewritten core enables massively parallel
        operations, perfect for complex CI/CD and multi-threaded applications.

      • **Microsecond Auto-Healing:** On-the-fly version conflict resolution that is
        orders of magnitude faster than traditional package managers.

      • **Instant Version Swapping:** Dynamically switch between conflicting packages
        or entire Python interpreters mid-script, without virtualenvs.
        
    Omnipkg is the high-performance alternative to managing countless virtualenvs
    and Docker images, built for developers and data scientists who demand
    maximum flexibility and speed.
  doc_url: https://github.com/1minds3t/omnipkg/tree/main/docs
  dev_url: https://github.com/1minds3t
extra:
  recipe-maintainers:
    - 1minds3t
