{% set name = "omnipkg" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 191b16427c1e86aefb39e95bed1899e9330926fbb5c5b53005c66ceb28299e5d

build:
  number: 1  # Reset for new version
  script:
    # Unix/Mac: Use the build python, but force install to the ARM location (${PREFIX})
    - python -m pip install . --no-deps --no-build-isolation --prefix "${PREFIX}" -vv  # [unix]
    
    # Windows: Just use standard pip (it knows where to go automatically)
    - python -m pip install . --no-deps --no-build-isolation -vv                       # [win]
    
  entry_points:
    - omnipkg = omnipkg.cli:main
    - 8pkg = omnipkg.cli:main
    - 8PKG = omnipkg.cli:main
    - OMNIPKG = omnipkg.cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=61.0
  run:
    - python
    - requests >=2.20
    - psutil >=5.9.0
    - typer >=0.4.0
    - rich >=10.0.0
    - filelock >=3.20.1
    - packaging >=23.0
    - tomli  # [py<311]
    - authlib >=1.6.5
    - aiohttp >=3.13.3
    - safety >=3.7.0  # [py<314]
    - marshmallow >=4.1.2
    - pip-audit >=2.6.0  # [py>=314]
    - uv >=0.9.6  # [not ppc64le]
    - urllib3 >=1.26.19
    - tqdm >=4.67.1
    - typing-extensions >=4.0.0
    - flask >=2.0
    - flask-cors >=3.0

test:
  # This selector skips tests when building osx-arm64 on an Intel runner
  requires:
    - pip
  imports:
    - omnipkg            # [build_platform == target_platform]
  commands:
    - omnipkg --version  # [build_platform == target_platform]

about:
  home: https://omnipkg.pages.dev/
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver. One environment. Infinite packages. Zero conflicts.'
  description: |
    OmniPkg is a distributed Python runtime hypervisor enabling concurrent, 
    zero-copy multi-framework orchestration.
    
    Platform Support:
    - Linux: x86_64, aarch64/ARM64, ppc64le
    - macOS: x86_64 (Intel), arm64 (Apple Silicon)
    - Windows: x86_64, ARM64
    
    Key Features:
    - Microsecond package activation (~50Î¼s)
    - Cross-platform daemon with native fork/no-fork modes
    - Concurrent multi-version package loading
    - Zero-copy multi-framework orchestration
    - Smart dependency resolution with snapshot restoration
    - Live daemon monitoring dashboard
  doc_url: https://omnipkg.readthedocs.io/en/latest/
  dev_url: https://github.com/1minds3t/omnipkg

extra:
  recipe-maintainers:
    - 1minds3t
