{% set name = "omnipkg" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 832c9ac4aef1999225e0c48053c3882cb56c29b9c1919b78629852fb4bb3220b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
  entry_points:
    - omnipkg = omnipkg.cli:main
    - 8pkg = omnipkg.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - packaging >=23.0
    - requests >=2.20
    - filelock >=3.9
    - tomli
    - tqdm
    - safety >=3.0
    - aiohttp
    - uv

test:
  imports:
    - omnipkg
  commands:
    - omnipkg --version

about:
  home: https://github.com/1minds3t/omnipkg
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver. One environment. Infinite packages. Zero conflicts.'
  description: |
    Omnipkg is a next-generation Python dependency manager that solves the
    classic problems of pip, conda, and Docker by enabling multiple package
    versions and Python interpreters to coexist in a single environment.
    Key features:
      • Dynamic version switching: swap between NumPy, TensorFlow, or any package mid-script.  
      • Multi-interpreter freedom: run Python 3.8, 3.11, and beyond in one process.  
      • Auto-healing: automatically detect and fix broken dependencies at runtime.  
      • Bubble isolation: install conflicting versions side by side without virtualenvs.  
      • SQLite/Redis intelligence: instant lookups, conflict resolution, and rollback.  
    Omnipkg is designed for researchers, quants, and engineers who demand
    speed, reproducibility, and zero-friction workflows across complex
    dependency stacks. It provides a robust alternative to pipx, uv, poetry,
    and Docker, all in one tool. Optional: omnipkg can use Redis (v5.0+) for improved speed.
  doc_url: https://github.com/1minds3t/omnipkg/tree/main/docs
  dev_url: https://github.com/1minds3t

extra:
  recipe-maintainers:
    - 1minds3t
