package:
  name: omnipkg
  version: 1.5.0

source:
  url: https://pypi.org/packages/source/o/omnipkg/omnipkg-1.5.0.tar.gz
  sha256: cab86e7ceb3a7d9acc308598361c983e5a97247dddc914e933ec4df146c80d4c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - omnipkg = omnipkg.cli:main
    - 8pkg = omnipkg.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - redis >=4.5.0
    - uv >=0.1.0
    - requests >=2.28.0
    - rich >=13.0.0
    - click >=8.1.0
    - pyyaml >=6.0.0
    - packaging >=21.0

test:
  commands:
    - omnipkg --help
    - 8pkg --help
    - python -c "import omnipkg; print('Import successful')"

about:
  home: https://github.com/1minds3t/omnipkg
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver - One environment, infinite versions, zero conflicts'
  description: |
    omnipkg is an intelligent, self-healing runtime orchestrator that breaks 
    the fundamental laws of Python environments. Run multiple Python versions 
    and package versions concurrently in the same environment without conflicts.
  doc_url: https://github.com/1minds3t/omnipkg
  dev_url: https://github.com/1minds3t/omnipkg
